name: Build

on:
  push:
    branches: main
    tags:
      - v0.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build Linux version
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-linux-gnu

      - name: Build Windows version
        run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-windows-gnu

      - name: Create Linux Tarball
        run: tar czvf pagebreak.tar.gz -C zig-out/bin/ pagebreak

      - name: Create Windows Zip
        run: 7z a pagebreak.zip ./zig-out/bin/pagebreak.exe

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pagebreak.tar.gz
            pagebreak.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
